### PR TITLE
Update to latest upstream. fixes WP_HOME in .environment

### LINKED ISSUE #46: WP_HOME not set correctly in .environment
Identical to https://github.com/platformsh-templates/wordpress-bedrock/issues/65 

Currently, .environment sets `WP_HOME` as 
`export WP_HOME=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select(.value.primary == true) | .key')` 
which returns the default route _with a trailing slash_. While not explicitly stated, it is implied in the docs that`WP_HOME` should not include a trailing slash. Bedrock, in their [application.php file builds on this assumption when assigning the value ](https://github.com/roots/bedrock/blob/master/config/application.php#L62)for `WP_CONTENT_URL`.  Since we are including the trailing slash, generated pages end up with a double slash between the domain and the location of  wp-content (`app` in the case of bedrock). 

Example:
https://main-bvxea6i-dwo6kco2adisc.ca-1.platformsh.site//app/themes/twentytwentytwo/style.css?ver=1.2
vs
https://main-bvxea6i-dwo6kco2adisc.ca-1.platformsh.site/app/themes/twentytwentytwo/style.css?ver=1.2

We need to chop off the trailing slash from the returned route before assigning it to `WP_HOME`.

Then, because we're removing the slash, we'll need to add it between `WP_HOME` and `wp` in the next line when assigning the value to `WP_SITEURL`

### PR DESCRIPTION
**Pull request by gilzow**
Closes #46

### CODE REVIEW

**Comment by gilzow** [comment]
Latest push addresses [issue #75 from wordpress-bedrock](https://github.com/platformsh-templates/wordpress-bedrock/issues/75).

**Comment by chadwcarlson** [comment]
@gilzow https://pr-47-i3bib2i-rggkfglt3j3yo.eu-3.platformsh.site/

```
Deprecated: Return type of Requests_Cookie_Jar::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Cookie/Jar.php on line 63

Deprecated: Return type of Requests_Cookie_Jar::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Cookie/Jar.php on line 73

Deprecated: Return type of Requests_Cookie_Jar::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Cookie/Jar.php on line 89

Deprecated: Return type of Requests_Cookie_Jar::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Cookie/Jar.php on line 102

Deprecated: Return type of Requests_Cookie_Jar::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Cookie/Jar.php on line 111

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 40

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 51

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetSet($key, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 68

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::offsetUnset($key) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 82

Deprecated: Return type of Requests_Utility_CaseInsensitiveDictionary::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/web/wp/wp-includes/Requests/Utility/CaseInsensitiveDictionary.php on line 91
```

**Comment by gilzow** [comment]
see : [Deprecated errors on PHP 8.1](https://core.trac.wordpress.org/ticket/54672)
Marking as draft until we can investigate.

**Comment by gilzow** [comment]
Closing as no longer relevant

**Pull request closed without merging**
